// Generated by scripts/generate-contract-projections.mjs. Do not edit.
pub const CONTRACT_CATALOG_FINGERPRINT: &str =
    "6e6b1621aed94ab0a378cd424996f78535d5c1da20b18ab942e63413561fb3a1";
pub const SERVICE_IDS: &[&str] = &[
    "viewit.document.parse",
    "viewit.document.render",
    "viewit.document.edit",
    "viewit.archive.list",
    "viewit.archive.read-entry",
    "viewit.archive.extract",
    "viewit.font.inspect",
    "viewit.media.play",
    "viewit.media.inspect",
    "viewit.media.transcode",
    "viewit.host.save-as",
];

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ProviderContract {
    pub id: &'static str,
    pub package_id: &'static str,
    pub service: &'static str,
    pub contract_version: u32,
    pub runtime: &'static str,
    pub trust_class: &'static str,
}

pub const PROVIDERS: &[ProviderContract] = &[
    ProviderContract {
        id: "office-universal.parse",
        package_id: "office-universal",
        service: "viewit.document.parse",
        contract_version: 1,
        runtime: "android-dex-jni",
        trust_class: "trusted-in-process",
    },
    ProviderContract {
        id: "pptx-vanilla.render",
        package_id: "pptx-vanilla",
        service: "viewit.document.render",
        contract_version: 1,
        runtime: "webview-js",
        trust_class: "trusted-in-process",
    },
    ProviderContract {
        id: "compression-universal.list",
        package_id: "compression-universal",
        service: "viewit.archive.list",
        contract_version: 1,
        runtime: "android-dex-jni",
        trust_class: "trusted-in-process",
    },
    ProviderContract {
        id: "compression-universal.read-entry",
        package_id: "compression-universal",
        service: "viewit.archive.read-entry",
        contract_version: 1,
        runtime: "android-dex-jni",
        trust_class: "trusted-in-process",
    },
    ProviderContract {
        id: "compression-universal.extract",
        package_id: "compression-universal",
        service: "viewit.archive.extract",
        contract_version: 1,
        runtime: "android-dex-jni",
        trust_class: "trusted-in-process",
    },
    ProviderContract {
        id: "font-universal.inspect",
        package_id: "font-universal",
        service: "viewit.font.inspect",
        contract_version: 1,
        runtime: "android-dex-jni",
        trust_class: "trusted-in-process",
    },
    ProviderContract {
        id: "iwork-universal.parse",
        package_id: "iwork-universal",
        service: "viewit.document.parse",
        contract_version: 1,
        runtime: "android-dex-jni",
        trust_class: "trusted-in-process",
    },
    ProviderContract {
        id: "player-base.play",
        package_id: "player-base",
        service: "viewit.media.play",
        contract_version: 1,
        runtime: "webview-js",
        trust_class: "trusted-in-process",
    },
    ProviderContract {
        id: "editor-base.edit",
        package_id: "editor-base",
        service: "viewit.document.edit",
        contract_version: 1,
        runtime: "webview-js",
        trust_class: "trusted-in-process",
    },
    ProviderContract {
        id: "ffmpeg-transcoder.transcode",
        package_id: "ffmpeg-transcoder",
        service: "viewit.media.transcode",
        contract_version: 1,
        runtime: "android-dex-jni",
        trust_class: "trusted-in-process",
    },
];
