// Generated by scripts/generate-contract-projections.mjs. Do not edit.
package ai.viewit.app

object ViewItContractCatalog {
    const val FINGERPRINT = "6e6b1621aed94ab0a378cd424996f78535d5c1da20b18ab942e63413561fb3a1"
    val serviceIds = listOf("viewit.document.parse", "viewit.document.render", "viewit.document.edit", "viewit.archive.list", "viewit.archive.read-entry", "viewit.archive.extract", "viewit.font.inspect", "viewit.media.play", "viewit.media.inspect", "viewit.media.transcode", "viewit.host.save-as")
    val providers = listOf(
        ProviderContract("office-universal.parse", "office-universal", "viewit.document.parse", 1, "android-dex-jni", "trusted-in-process"),
        ProviderContract("pptx-vanilla.render", "pptx-vanilla", "viewit.document.render", 1, "webview-js", "trusted-in-process"),
        ProviderContract("compression-universal.list", "compression-universal", "viewit.archive.list", 1, "android-dex-jni", "trusted-in-process"),
        ProviderContract("compression-universal.read-entry", "compression-universal", "viewit.archive.read-entry", 1, "android-dex-jni", "trusted-in-process"),
        ProviderContract("compression-universal.extract", "compression-universal", "viewit.archive.extract", 1, "android-dex-jni", "trusted-in-process"),
        ProviderContract("font-universal.inspect", "font-universal", "viewit.font.inspect", 1, "android-dex-jni", "trusted-in-process"),
        ProviderContract("iwork-universal.parse", "iwork-universal", "viewit.document.parse", 1, "android-dex-jni", "trusted-in-process"),
        ProviderContract("player-base.play", "player-base", "viewit.media.play", 1, "webview-js", "trusted-in-process"),
        ProviderContract("editor-base.edit", "editor-base", "viewit.document.edit", 1, "webview-js", "trusted-in-process"),
        ProviderContract("ffmpeg-transcoder.transcode", "ffmpeg-transcoder", "viewit.media.transcode", 1, "android-dex-jni", "trusted-in-process")
    )
}

data class ProviderContract(
    val id: String,
    val packageId: String,
    val service: String,
    val contractVersion: Int,
    val runtime: String,
    val trustClass: String,
)
