export interface FormatProvider {
  id: string;
  name: string;
  formats: string[];
  installed?: boolean;
  runtime?: string;
  base?: string;
}

export type FormatCapability =
  | { kind: "installed-plugin"; ext: string; plugin: FormatProvider; available: FormatProvider[] }
  | { kind: "built-in"; ext: string; available: FormatProvider[] }
  | { kind: "available-plugin"; ext: string; available: FormatProvider[] }
  | { kind: "unsupported"; ext: string; available: [] };

const BUILT_IN_FORMATS = new Set([
  "txt",
  "text",
  "log",
  "md",
  "markdown",
  "mdown",
  "mkdn",
  "mdx",
  "json",
  "jsonc",
  "json5",
  "jsonl",
  "ndjson",
  "csv",
  "tsv",
  "yaml",
  "yml",
  "xml",
  "html",
  "htm",
  "xhtml",
  "css",
  "ini",
  "cfg",
  "conf",
  "toml",
  "pdf",
  "png",
  "jpg",
  "jpeg",
  "webp",
  "gif",
  "bmp",
  "tif",
  "tiff",
  "svg",
  "svgz",
  "heic",
  "heif",
  "avif",
  "psd",
  "dng",
  "cr2",
  "cr3",
  "nef",
  "arw",
  "orf",
  "rw2",
  "raf",
  "srw",
  "pef",
  "ico",
  "icns",
  "jfif",
  "epub",
  "mobi",
  "azw3",
  "fb2",
  "lrf",
  "pdb",
  "snb",
  "ttf",
  "otf",
  "woff",
  "woff2",
  "ttc",
  "pfb",
  "cff",
  "dfont",
  "sfd",
  "ps",
  "zip",
  "tar",
  "tgz",
  "gz",
  "tbz2",
  "bz2",
  "txz",
  "xz",
  "tzst",
  "zst",
  "lz4",
  "tlz",
  "lzma",
  "7z",
  "rar",
  "docx",
  "docm",
  "dotx",
  "dotm",
  "xlsx",
  "xlsm",
  "xlsb",
  "xls",
  "pptx",
  "pptm",
  "potx",
  "odt",
  "ott",
  "ods",
  "odp",
  "doc",
  "ppt",
  "rtf",
  "pages",
  "numbers",
  "key",
  "plist",
  "ics",
  "vcf",
  "mp4",
  "m4v",
  "webm",
  "mkv",
  "mov",
  "avi",
  "mpg",
  "mpeg",
  "3gp",
  "wmv",
  "flv",
  "ts",
  "asf",
  "f4v",
  "hevc",
  "m2ts",
  "m2v",
  "mjpeg",
  "mts",
  "mxf",
  "ogv",
  "rm",
  "swf",
  "vob",
  "wtv",
  "mp3",
  "m4a",
  "aac",
  "flac",
  "ogg",
  "wav",
  "wma",
  "opus",
  "aif",
  "aiff",
  "ac3",
  "au",
  "caf",
  "dts",
  "m4r",
  "mp2",
  "oga",
  "ra",
  // additional raw/compound image formats (rendered as ImageRaw)
  "cur",
  "dds",
  "erf",
  "exr",
  "fts",
  "hdr",
  "jp2",
  "jpe",
  "jps",
  "mng",
  "nrw",
  "pam",
  "pbm",
  "pcd",
  "pcx",
  "pes",
  "pfm",
  "pgm",
  "picon",
  "pict",
  "pnm",
  "ppm",
  "ras",
  "sfw",
  "sgi",
  "tga",
  "wbmp",
  "wpg",
  "x3f",
  "xbm",
  "xcf",
  "xpm",
  "xwd",
  "djvu",
  "djv",
  // plain text / metadata
  "readme",
  "gitignore",
  "gitattributes",
  "editorconfig",
  "dockerignore",
  "npmignore",
  "nfo",
  "srt",
  "vtt",
  "sub",
  "rst",
  "adoc",
  "asc",
  "strings",
  "desktop",
  "env",
  "config",
  "ipynb",
  "lock",
  // application / config / build code (rendered as code text)
  "rs",
  "ts",
  "tsx",
  "js",
  "jsx",
  "mjs",
  "cjs",
  "py",
  "pyw",
  "go",
  "c",
  "cc",
  "cpp",
  "cxx",
  "h",
  "hpp",
  "hh",
  "java",
  "kt",
  "kts",
  "swift",
  "sh",
  "bash",
  "zsh",
  "fish",
  "sql",
  "lua",
  "php",
  "rb",
  "ex",
  "exs",
  "erl",
  "hrl",
  "hs",
  "ml",
  "mli",
  "clj",
  "cljs",
  "scala",
  "sc",
  "r",
  "jl",
  "vim",
  "ps1",
  "bat",
  "cmd",
  "cs",
  "fs",
  "fsx",
  "dart",
  "zig",
  "nim",
  "v",
  "sv",
  "vhd",
  "vhdl",
  "asm",
  "s",
  "gradle",
  "cmake",
  "make",
  "mk",
  "dockerfile",
  "proto",
  "graphql",
  "gql",
  "vue",
  "svelte",
  "astro",
  "wat",
  "patch",
  "diff",
  "class",
  "htaccess",
  "kml",
  "kmz",
]);

const MIME_FORMATS: Record<string, string> = {
  // documents
  "application/pdf": "pdf",
  "application/json": "json",
  "application/rtf": "rtf",
  "application/epub+zip": "epub",
  "application/x-mobipocket-ebook": "mobi",
  "application/msword": "doc",
  "application/vnd.ms-word": "doc",
  "application/vnd.ms-excel": "xls",
  "application/vnd.ms-powerpoint": "ppt",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document": "docx",
  "application/vnd.ms-word.document.macroenabled.12": "docm",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": "xlsx",
  "application/vnd.ms-excel.sheet.macroenabled.12": "xlsm",
  "application/vnd.ms-excel.sheet.binary.macroenabled.12": "xlsb",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation": "pptx",
  "application/vnd.ms-powerpoint.presentation.macroenabled.12": "pptm",
  "application/vnd.oasis.opendocument.text": "odt",
  "application/vnd.oasis.opendocument.spreadsheet": "ods",
  "application/vnd.oasis.opendocument.presentation": "odp",
  "application/vnd.apple.pages": "pages",
  "application/vnd.apple.numbers": "numbers",
  "application/vnd.apple.keynote": "key",
  // archives
  "application/zip": "zip",
  "application/x-tar": "tar",
  "application/gzip": "gz",
  "application/x-gzip": "gz",
  "application/x-7z-compressed": "7z",
  "application/x-rar-compressed": "rar",
  // text
  "text/markdown": "md",
  "text/csv": "csv",
  "text/plain": "txt",
  "text/html": "html",
  "text/xml": "xml",
  "application/xml": "xml",
  "text/yaml": "yaml",
  "application/x-yaml": "yaml",
  "text/x-json": "json",
  "text/javascript": "js",
  "application/javascript": "js",
  "text/x-ics": "ics",
  "text/calendar": "ics",
  "text/vcard": "vcf",
  "text/x-vcard": "vcf",
  "application/x-desktop": "desktop",
  // images
  "image/png": "png",
  "image/jpeg": "jpg",
  "image/webp": "webp",
  "image/gif": "gif",
  "image/bmp": "bmp",
  "image/tiff": "tiff",
  "image/svg+xml": "svg",
  "image/x-icon": "ico",
  "image/heic": "heic",
  "image/heif": "heif",
  "image/avif": "avif",
  "image/vnd.adobe.photoshop": "psd",
  // fonts
  "font/ttf": "ttf",
  "font/otf": "otf",
  "font/woff": "woff",
  "font/woff2": "woff2",
  "font/collection": "ttc",
  // audio
  "audio/mpeg": "mp3",
  "audio/mp4": "m4a",
  "audio/x-m4a": "m4a",
  "audio/aac": "aac",
  "audio/flac": "flac",
  "audio/ogg": "ogg",
  "audio/opus": "opus",
  "audio/wav": "wav",
  "audio/x-wav": "wav",
  "audio/aiff": "aiff",
  "audio/x-aiff": "aif",
  "audio/x-ms-wma": "wma",
  // video
  "video/mp4": "mp4",
  "video/quicktime": "mov",
  "video/webm": "webm",
  "video/x-matroska": "mkv",
  "video/x-msvideo": "avi",
  "video/mpeg": "mpeg",
  "video/x-flv": "flv",
  "video/mp2t": "ts",
  "video/3gpp": "3gp",
  "video/x-ms-asf": "asf",
  "video/ogg": "ogv",
  "video/x-ms-wmv": "wmv",
};

export function normalizeFormat(value: string | null | undefined): string {
  return (value ?? "").trim().toLowerCase().replace(/^\./, "");
}

export function formatFromFile(name: string | null | undefined, mime?: string | null): string {
  const base = (name ?? "").split(/[?#]/, 1)[0].split(/[/\\]/).pop() ?? "";
  const dot = base.lastIndexOf(".");
  if (dot >= 0 && dot < base.length - 1) return normalizeFormat(base.slice(dot + 1));
  const normalizedMime = (mime ?? "").toLowerCase().split(";", 1)[0].trim();
  return MIME_FORMATS[normalizedMime] ?? "";
}

export function isBuiltInFormat(ext: string): boolean {
  return BUILT_IN_FORMATS.has(normalizeFormat(ext));
}

export function providerSupportsFormat(provider: FormatProvider, ext: string): boolean {
  const normalized = normalizeFormat(ext);
  return provider.formats.some((format) => normalizeFormat(format) === normalized);
}

export function resolveFormatCapability(
  ext: string,
  installed: FormatProvider[] = [],
  catalog: FormatProvider[] = [],
): FormatCapability {
  const normalized = normalizeFormat(ext);
  const installedPlugin = installed.find(
    (plugin) =>
      providerSupportsFormat(plugin, normalized) &&
      (plugin.base ?? "view") === "view" &&
      plugin.runtime !== "js",
  );
  const seen = new Set<string>();
  const available = catalog.filter((plugin) => {
    if (
      !providerSupportsFormat(plugin, normalized) ||
      (plugin.base ?? "view") !== "view" ||
      plugin.runtime === "js" ||
      installed.some((item) => item.id === plugin.id && providerSupportsFormat(item, normalized)) ||
      seen.has(plugin.id)
    ) {
      return false;
    }
    seen.add(plugin.id);
    return true;
  });
  if (installedPlugin)
    return { kind: "installed-plugin", ext: normalized, plugin: installedPlugin, available };
  if (isBuiltInFormat(normalized)) return { kind: "built-in", ext: normalized, available };
  if (available.length > 0) return { kind: "available-plugin", ext: normalized, available };
  return { kind: "unsupported", ext: normalized, available: [] };
}
