// Single deterministic stress fixture shared by web, Android, and desktop E2E.
//
// It exercises the core fmt-text parse path ("a file parsed into text") with a
// multi-megabyte plain-text document that also contains very long lines, so a
// regression in chrome freezing or overflow containment shows up on every
// platform from one artifact.
//
// Content is generated by an xorshift32 PRNG with a fixed seed: byte-identical
// output on every platform and run, no network, no committed binary blob.

export const STRESS_FILE_NAME = "stress.log";
export const STRESS_NEEDLE = "NEEDLE-ZQX-7788";
export const STRESS_NEEDLE_LINE = 12345;

const WORDS = [
  "viewit",
  "stress",
  "fixture",
  "render",
  "chunk",
  "frozen",
  "chrome",
  "line",
  "token",
  "payload",
];

function makeRand(seed) {
  let s = seed | 0;
  return () => {
    s ^= s << 13;
    s ^= s >>> 17;
    s ^= s << 5;
    return (s >>> 0) / 0xffffffff;
  };
}

export function makeStressText({ megabytes = 6 } = {}) {
  const targetBytes = Math.round(megabytes * 1024 * 1024);
  const rand = makeRand(0x2545f491);
  const parts = [];
  let size = 0;
  let lineNo = 0;
  while (size < targetBytes) {
    lineNo++;
    let line;
    if (lineNo % 500 === 0) {
      // Very long line: must never widen the app shell or trigger WebView
      // zoom-to-fit — the shell has to contain it inside its own scroller.
      line = `L${lineNo} WIDE ${"x".repeat(4096)}`;
    } else if (lineNo === STRESS_NEEDLE_LINE) {
      line = `L${lineNo} marker ${STRESS_NEEDLE} end`;
    } else {
      const n = 8 + Math.floor(rand() * 24);
      const w = [];
      for (let i = 0; i < n; i++) w.push(WORDS[Math.floor(rand() * WORDS.length)]);
      line = `L${lineNo} ${w.join(" ")}`;
    }
    parts.push(line);
    size += line.length + 1;
  }
  return parts.join("\n");
}
